[project]
name = "aoc2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipdb>=0.13.13",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "shapely>=2.1.2",
]
